(function(root,f){if(typeof module==='object'&&module.exports)module.exports=f();else root.AssetCore=f()})(this,function(){
const VERSION='10.6.0';const num=v=>{const n=Number(String(v??'').replace(/[,$₩원주\s]/g,'').replace(/,/g,''));return Number.isFinite(n)?n:0};const clone=o=>JSON.parse(JSON.stringify(o));const id=p=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;const currency=s=>s.market==='US'?'USD':'KRW';
function empty(){return{version:VERSION,stocks:[],trades:[],cash:{KRW:0,USD:0},realized:{KRW:0,USD:0}}}function money(v,c){return c==='USD'?'$'+num(v).toLocaleString('en-US',{maximumFractionDigits:4}):'₩'+Math.round(num(v)).toLocaleString('ko-KR')}
function trade(st,stockId,side,price,qty){const s=st.stocks.find(x=>x.id===stockId);if(!s)throw Error('종목 없음');price=num(price);qty=num(qty);if(price<=0||qty<=0)throw Error('가격과 수량 확인');if(side==='sell'&&qty>s.shares)throw Error('보유수량 초과');const before=clone(s);let realized=0;if(side==='buy'){const total=s.avg*s.shares+price*qty;s.shares+=qty;s.avg=total/s.shares;st.cash[currency(s)]-=price*qty}else{realized=(price-s.avg)*qty;s.shares-=qty;st.cash[currency(s)]+=price*qty;st.realized[currency(s)]+=realized;if(!s.shares)s.avg=0}const t={id:id('t'),date:new Date().toISOString(),stockId,sName:s.name,side,price,qty,currency:currency(s),realized,before,after:clone(s),undone:false};st.trades.unshift(t);return t}
function undo(st,tid){const t=st.trades.find(x=>x.id===tid);if(!t||t.undone)throw Error('취소 불가');const s=st.stocks.find(x=>x.id===t.stockId);Object.assign(s,clone(t.before));const amount=t.price*t.qty;if(t.side==='buy')st.cash[t.currency]+=amount;else{st.cash[t.currency]-=amount;st.realized[t.currency]-=t.realized}t.undone=true}
const clean=l=>l.replace(/[|•·]/g,' ').replace(/\s+/g,' ').trim();const badName=/^(내 평균|평균|현재가|평가금|평가손익|수익률|증권홈|장마감|프리마켓|원|주|KRW|USD)$/i;
function parseOCR(text,known=[]){const lines=String(text||'').split(/\r?\n/).map(clean).filter(Boolean);const rows=[];const knownSorted=[...known].sort((a,b)=>b.name.length-a.name.length);
function candidateName(line){const found=knownSorted.find(k=>line.replace(/\s/g,'').includes(k.name.replace(/\s/g,'')));if(found)return found.name;let x=line.replace(/\b\d+[.,]?\d*\s*주\b/g,'').replace(/내 평균.*$/,'').replace(/[₩$]?\d[\d,]*(?:\.\d+)?\s*원?/g,'').trim();if(x.length<2||badName.test(x)||!/[가-힣A-Za-z]/.test(x))return'';return x.slice(0,40)}
for(let i=0;i<lines.length;i++){const name=candidateName(lines[i]);if(!name)continue;if(rows.some(r=>r.name===name))continue;const win=lines.slice(i,Math.min(lines.length,i+7));let shares=0,avg=0,current=0;for(const l of win){let m=l.match(/([\d,.]+)\s*주/);if(m&&!shares)shares=num(m[1]);m=l.match(/(?:내\s*평균|평균(?:단가)?)\s*[:：]?\s*[₩$]?\s*([\d,.]+)/i);if(m&&!avg)avg=num(m[1]);m=l.match(/(?:현재가|현재)\s*[:：]?\s*[₩$]?\s*([\d,.]+)/i);if(m&&!current)current=num(m[1])}
const knownStock=knownSorted.find(k=>k.name===name);rows.push({id:id('ocr'),selected:true,name,market:knownStock?.market||(/[A-Za-z]{2,}/.test(name)&&!/[가-힣]/.test(name)?'US':'KR'),shares,avg,current,confidence:(shares>0?30:0)+(avg>0?30:0)+(current>0?25:0)+(knownStock?15:0)})}
return rows.filter(r=>r.shares||r.avg||r.current||known.some(k=>k.name===r.name))}
function applyOCR(st,rows){const result={created:0,updated:0,skipped:0};for(const r of rows.filter(x=>x.selected)){if(!r.name.trim()){result.skipped++;continue}let s=st.stocks.find(x=>x.name.replace(/\s/g,'').toLowerCase()===r.name.replace(/\s/g,'').toLowerCase());if(!s){s={id:id('s'),name:r.name.trim(),market:r.market||'KR',shares:num(r.shares),avg:num(r.avg),current:num(r.current),target:0};st.stocks.push(s);result.created++}else{if(num(r.shares)>=0)s.shares=num(r.shares);if(num(r.avg)>0)s.avg=num(r.avg);if(num(r.current)>0)s.current=num(r.current);s.market=r.market||s.market;result.updated++}}return result}
return{VERSION,num,clone,id,currency,empty,money,trade,undo,parseOCR,applyOCR}});
